name: Release Build
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    # - name: Get version from tag
    #   id: get_version
    #   run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build for multiple platforms
      run: |
        make build-all -j$(nproc)
    - name: Create release
      if: ${{ contains(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/ollama-proxy-windows-amd64.exe
          dist/ollama-proxy-windows-arm64.exe
          dist/ollama-proxy-linux-amd64
          dist/ollama-proxy-linux-arm64
          dist/ollama-proxy-darwin-amd64
          dist/ollama-proxy-darwin-arm64
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for ${{ github.ref_name }}
          
          ### 支持的平台
          - Windows x86_64
          - Windows ARM64
          - Linux x86_64
          - Linux ARM64
          - macOS x86_64
          - macOS ARM64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
